export const pageTranslations = {
  en: {
    aboutPage: {
      hero: { badge: "Our Story", heading: "We believe travel should feel human", sub: "NativeWay was born from a simple frustration — the best experiences in any city are hidden from the people who need them most. We're changing that." },
      mission: [
        { title: "Our Mission", text: "To close the gap between tourists and locals — making every traveler feel like they belong, and every local feel heard." },
        { title: "Our Vision", text: "A world where travel creates real cultural exchange, supports local economies, and leaves destinations better than we found them." },
        { title: "Our Approach", text: "Technology in service of human connection. We build tools that get out of the way and let the real experience shine through." },
      ],
      origin: {
        badge: "The Origin", heading: "Born from a bad meal in Barcelona",
        p1: "It was 2022. Mateo had just paid €28 for a paella that came out of a microwave, three blocks from La Rambla. Meanwhile, a local on the metro told him about a family-run place in Gràcia — open for 40 years, full of regulars, €12 for the best rice he'd ever eat.",
        p2: "\"Why isn't this information findable?\" he asked. The answer was uncomfortable: because the platforms that dominate travel discovery are optimised for advertising spend, not authenticity.",
        p3: "He called Aiko that night. Six months later, they had a prototype. Two years later, 1,200 people are on the waitlist. The paella restaurant in Gràcia? It's still going strong.",
      },
      timeline: {
        badge: "Journey", heading: "How we got here",
        milestones: [
          { year: "2022", title: "The idea sparks", description: "Mateo and Aiko meet at a hostel in Lisbon and bond over the same frustration: the best local spots are invisible to tourists." },
          { year: "2023", title: "Building the foundation", description: "First prototype tested with 200 locals across 5 cities. The feedback was overwhelming — locals wanted a platform to share their city." },
          { year: "2024", title: "The team grows", description: "Rania and Diego join. NativeWay expands its local network to 20 cities and begins closed beta testing." },
          { year: "2025", title: "Waitlist opens", description: "Over 1,200 travelers sign up in the first month. Partner locals in 50+ cities curate their first collections." },
          { year: "2026", title: "Launch year", description: "NativeWay prepares for public launch. The mission is simple: make every traveler feel like a local." },
        ],
      },
      team: { badge: "The Team", heading: "Built by travelers, for travelers" },
      cta: { heading: "Ready to travel the native way?", sub: "Join the waitlist and be first to experience it.", button: "Get Early Access" },
    },
    featuresPage: {
      hero: { badge: "Features", heading: "Everything built with one principle", sub: "Six pillars. One platform. Everything you need from the moment you start dreaming about a trip to the moment you get home." },
      pillarNav: "Jump to section",
      pillars: [
        { category: "Plan", tagline: "Build your trip, your way", description: "NativeWay's planning suite goes far beyond a basic itinerary builder. Create trips from scratch or let our AI generate a full day-by-day plan based on your dates, budget, travel style, and the real local spots in our database.", items: [{ title: "Create Trips", description: "Build multi-day trip boards with dates, destinations, and saved places all in one view." }, { title: "AI Itineraries", description: "Describe your trip in plain language and get a full itinerary built from verified local recommendations." }, { title: "Route Planning", description: "Optimise the order of your stops automatically so you're not doubling back across the city." }] },
        { category: "Discover", tagline: "Find what the guidebooks miss", description: "Discovery on NativeWay is powered by people, not algorithms. Every place in our database was added by someone who actually lives there. Browse curated destination guides, filter by neighbourhood or vibe.", items: [{ title: "Local Places", description: "Every pin on the map comes from a verified resident — restaurants, parks, viewpoints, shops, and more." }, { title: "Hidden Gems", description: "A curated layer of spots that locals love but tourists almost never find. Anti-viral by design." }, { title: "Destination Guides", description: "Full neighbourhood-by-neighbourhood guides written and maintained by people who live in each city." }] },
        { category: "Collaborate", tagline: "Plan together, travel better", description: "Group travel is notoriously hard to organise. NativeWay's collaboration tools bring everyone onto the same page. Share trip boards, vote on options democratically, and use Party Mode when you're all on the ground together.", items: [{ title: "Party Mode", description: "Activate when your group arrives. See where everyone is, share live recommendations, and coordinate in real time." }, { title: "Voting", description: "Add candidate places to a shared board and let the group vote. No more endless WhatsApp threads." }, { title: "Group Planning", description: "Shared trip boards that every member can edit, comment on, and add to before and during the trip." }] },
        { category: "Manage", tagline: "All your travel admin in one place", description: "NativeWay handles the practical side of travel so you can focus on the experience. Store passport details, track visa requirements, and keep all your documents organised in one place.", items: [{ title: "Passport", description: "Store your passport info securely and get reminders before it expires — especially useful for last-minute trips." }, { title: "Visas", description: "Get destination-specific visa requirements, processing times, and links to the official application portals." }, { title: "Travel Collections", description: "Save places, articles, and tips into named collections you can revisit, share, or turn into a trip." }] },
        { category: "Connect", tagline: "Stories, conversations, community", description: "Travel is more meaningful when you share it. NativeWay's community layer lets travellers and locals exchange stories, ask questions, and build connections that extend beyond any single trip.", items: [{ title: "Blogs", description: "Write trip reports and local spotlights. The best stories get featured in destination guides." }, { title: "Messaging", description: "Direct messaging with locals and fellow travellers — ask for advice, say thank you, or stay in touch." }, { title: "Community", description: "Forums and threads organised by city. Ask before you go, share while you're there, reflect when you're back." }] },
        { category: "Premium", tagline: "Unlock the full NativeWay experience", description: "NativeWay's core is free. Premium unlocks richer AI planning, full offline cities, and access to our most exclusive local discoveries kept off the free tier to protect against overcrowding.", items: [{ title: "AI Enhancements", description: "Smarter itinerary generation, personalised daily replanning, and AI-powered Ask a Local summaries." }, { title: "Offline Access", description: "Download any city — maps, reviews, guides, and routes — and use everything without mobile data." }, { title: "Exclusive Discoveries", description: "Premium-only hidden gems kept off the public map to protect sensitive spots from over-tourism." }] },
      ],
      comingSoon: { badge: "Coming Soon", heading: "On the roadmap", items: [{ title: "Local Alerts", description: "Get notified about temporary closures, new openings, and time-sensitive local tips." }, { title: "Scam Warnings", description: "Residents flag tourist scams and overpriced areas in real time." }, { title: "Cultural Notes", description: "Etiquette tips and local customs written by residents who've seen tourists get it wrong." }, { title: "Trip Export", description: "Export your saved places and routes as a printable PDF or share with travel companions." }] },
      cta: { heading: "Want to be first to use these features?", sub: "Early access members get everything free for a full year.", button: "Join the Waitlist" },
    },
    howItWorksPage: {
      hero: { badge: "How It Works", heading: "From idea to experience — every step covered", sub: "NativeWay supports the full travel journey: planning before you go, discovering while you're there, collaborating with your group, and connecting with the community after." },
      phases: ["Plan", "Discover", "Collaborate", "Navigate", "Share"],
      steps: [
        { phase: "Before You Go", title: "Plan your trip", description: "Start by creating a trip in NativeWay. Set your destination, dates, and travel style. Our AI itinerary builder generates a full day-by-day plan using real local recommendations — not generic tourist content.", features: [{ label: "AI Itineraries", note: "Plain-language prompts → full local itinerary" }, { label: "Route Planning", note: "Stops ordered to minimise backtracking" }, { label: "Passport & Visas", note: "Check requirements before you book" }], tip: "Download your destination city before you leave — everything works offline once it's saved." },
        { phase: "Before You Go", title: "Discover local places", description: "Browse the local map, read destination guides written by residents, and save your must-visits. Use Hidden Gems to find spots that will never appear in a travel magazine.", features: [{ label: "Local Places", note: "Every pin placed by a verified resident" }, { label: "Hidden Gems", note: "Premium-curated spots kept off the public map" }, { label: "Destination Guides", note: "Neighbourhood-level guides by locals" }], tip: "Save places into named collections ('Day 1', 'Rainy Day Options') to keep your board organised." },
        { phase: "Travelling With Others", title: "Collaborate with your group", description: "Share your trip board with travel companions. Everyone can add suggestions, and the group votes on the options they like most. Activate Party Mode to coordinate in real time on the ground.", features: [{ label: "Voting", note: "Democratic shortlisting — everyone has a say" }, { label: "Party Mode", note: "Live group coordination when you're all there" }, { label: "Shared Boards", note: "Everyone edits the same trip plan" }], tip: "Set a voting deadline so planning doesn't drag on forever." },
        { phase: "On the Ground", title: "Navigate and experience", description: "Head out with your offline map, Native Routes, and local tips already downloaded. Follow a day route step by step, or free-explore with the local map as your guide.", features: [{ label: "Offline Maps", note: "Full navigation without mobile data" }, { label: "Native Routes", note: "Follow routes built by locals who know every shortcut" }, { label: "Ask a Local", note: "Real-time answers from verified residents" }], tip: "Mark places as visited as you go — it builds your personal travel history." },
        { phase: "After Your Trip", title: "Share and connect", description: "Write a trip blog, leave honest reviews, and message locals who helped you. Your perspective adds a valuable layer on top of the local voice and earns you community reputation.", features: [{ label: "Blogs", note: "Trip reports that help future travellers" }, { label: "Reviews", note: "Your honest take, layered onto local reviews" }, { label: "Travel Collections", note: "Save and organise everything for next time" }], tip: "The most useful reviews mention one specific thing no other review mentions." },
      ],
      locals: {
        heading: "For Locals",
        steps: [
          { number: "01", title: "Verify your residency", description: "Quick and private — we confirm you live in the city without storing sensitive documents. A utility bill or local ID is all it takes." },
          { number: "02", title: "Pin your favourite spots", description: "Add the places you genuinely love — your neighbourhood café, the park with the best view, the market stall that's been there since your grandparents' time." },
          { number: "03", title: "Write honest reviews", description: "Tell it like it is: best dish, worst time to visit, what the tourist photos don't show. Locals are the truth-tellers on NativeWay." },
          { number: "04", title: "Build a Native Route", description: "Chain your favourite spots into a day itinerary. Add context, history, and the journey between stops. Make it something you'd give to a friend." },
        ],
        note: "Locals earn reputation, recognition, and (coming soon) tips from grateful travellers.",
      },
      cta: { heading: "Ready to try it yourself?", sub: "Sign up for early access and be among the first to explore.", button: "Get Early Access" },
    },
    valuesPage: {
      hero: { badge: "Our Values", heading: "What we actually stand for", sub: "Values aren't a marketing page — they're the decisions we make when it costs us something. Here's what we've committed to, and why." },
      values: [
        { title: "Authenticity First", summary: "Every recommendation comes from real locals — residents, not influencers.", description: "We built NativeWay around a simple belief: the most valuable travel information comes from people who actually live somewhere. Not algorithms, not influencers, not outdated guidebooks.", principles: ["Locals must verify their residency before contributing", "No paid placements or sponsored recommendations", "Content is reviewed by multiple locals before being surfaced", "Transparency labels on every entry"], quote: "\"If my mum wouldn't eat there, it doesn't go on the map.\" — Rania, Head of Community" },
        { title: "Community-Driven", summary: "The whole ecosystem runs on mutual trust between locals and travellers.", description: "NativeWay is a living system that improves because locals contribute honestly and travellers respond with genuine appreciation. Both sides have obligations, both sides benefit.", principles: ["Locals earn reputation, not just thanks", "Travellers are expected to leave honest, specific feedback", "Community moderators flag bad actors", "Platform changes are informed by community input"], quote: "\"Honesty over being nice. We ask for both where possible, but honesty first.\" — Mateo, CEO" },
        { title: "Support Local", summary: "We deliberately direct tourism toward independent businesses and local culture.", description: "Mass tourism has hollowed out countless city centres. NativeWay actively routes attention and money toward the places that make a destination worth visiting.", principles: ["Independent businesses are always prioritised in discovery", "Chains are not surfaced in local recommendations", "Cultural and heritage sites receive dedicated promotion", "NativeWay donates 2% of revenue to local preservation funds"], quote: "\"The best souvenir you can take home is knowing you spent money somewhere that needed it.\" — Aiko, CTO" },
        { title: "Privacy by Design", summary: "Your data is yours. Full stop.", description: "The travel industry is built on data extraction. NativeWay is built on the opposite model. We make money when you find value in the app. That's the only incentive we need.", principles: ["No location data sold to third parties — ever", "No behavioural tracking for advertising", "Minimal data collection: only what the product needs", "Full data export and account deletion available at any time"], quote: "\"We could make more money selling your data. We chose not to.\" — Diego, Design" },
        { title: "Sustainable Travel", summary: "We think about the long-term health of destinations, not just visitor numbers.", description: "Overtourism destroys the very qualities that made a destination attractive. NativeWay consciously manages visitor flow to protect the places we love.", principles: ["Hidden Gems visibility is capped to prevent viral overcrowding", "Cultural etiquette guides on every destination page", "Off-season travel is promoted with seasonal local content", "Partnerships with local environmental groups"], quote: "\"We want the places we love to still be worth loving in 20 years.\" — Rania, Head of Community" },
        { title: "Radical Transparency", summary: "We tell you how the sausage is made — because you deserve to know.", description: "NativeWay publishes its content moderation guidelines, local verification process, and business model openly. If we change anything significant, we tell the community first.", principles: ["Public content moderation policy", "Open changelog of platform updates", "Business model clearly explained: subscription, no ads", "Community feedback published including critical"], quote: "\"Trust is built by showing your work. Every time.\" — Mateo, CEO" },
      ],
      commitment: { heading: "These aren't aspirations — they're constraints", p1: "We've turned our values into hard product rules. We can't insert a sponsored recommendation even if we wanted to — the system doesn't allow it. We can't sell location data — we don't collect it in a form that can be sold.", p2: "That's the difference between a value statement and a value. We build the constraints in." },
      cta: { heading: "Share our values? Come join us.", sub: "Early access is open — and free for the first year.", button: "Get Early Access" },
    },
  },

  zh: {
    aboutPage: {
      hero: { badge: "我们的故事", heading: "我们相信旅行应该充满人情味", sub: "NativeWay 源于一个简单的挫败感——每座城市中最好的体验，对最需要它们的人来说往往是隐形的。我们正在改变这一点。" },
      mission: [
        { title: "我们的使命", text: "弥合游客与当地人之间的鸿沟——让每位旅行者都感到融入，让每位当地人都感到被倾听。" },
        { title: "我们的愿景", text: "一个旅行能带来真实文化交流、支持本地经济并让目的地比我们到来时更美好的世界。" },
        { title: "我们的方法", text: "以技术服务人与人之间的连接。我们构建默默退居幕后、让真实体验自然绽放的工具。" },
      ],
      origin: {
        badge: "起源", heading: "源于巴塞罗那的一顿糟糕饭食",
        p1: "那是2022年。Mateo 刚刚在兰布拉大道三个街区外，花了28欧元吃了一份从微波炉里取出的海鲜饭。而地铁上一位当地人告诉他格拉西亚区有一家家庭餐厅——开了40年，座无虚席，12欧元就能吃到他这辈子最好的米饭。",
        p2: "\"为什么这些信息找不到？\"他自问。答案令人不安：因为主导旅游发现的平台优化的是广告投入，而非真实性。",
        p3: "当晚他打电话给 Aiko。六个月后他们有了原型。两年后，1200人加入了候补名单。格拉西亚区那家餐厅？依然生意兴隆。",
      },
      timeline: {
        badge: "历程", heading: "我们如何走到今天",
        milestones: [
          { year: "2022", title: "灵感闪现", description: "Mateo 和 Aiko 在里斯本一家青旅相遇，因同样的挫败感而结缘：最好的本地去处对游客来说几乎是隐形的。" },
          { year: "2023", title: "奠定基础", description: "在5座城市的200位当地人中测试了首个原型。反馈令人振奋——当地人渴望一个分享自己城市的平台。" },
          { year: "2024", title: "团队壮大", description: "Rania 和 Diego 加入。NativeWay 将本地网络扩展至20座城市并开始封闭测试。" },
          { year: "2025", title: "候补名单开放", description: "第一个月超过1200名旅行者注册。50多座城市的合作当地人精心策划了首批精选内容。" },
          { year: "2026", title: "发布年", description: "NativeWay 准备公开发布。使命很简单：让每位旅行者都感受到身为当地人的体验。" },
        ],
      },
      team: { badge: "团队", heading: "由旅行者创立，为旅行者服务" },
      cta: { heading: "准备好以本地方式旅行了吗？", sub: "加入候补名单，第一个体验它。", button: "提前获取" },
    },
    featuresPage: {
      hero: { badge: "功能介绍", heading: "一切基于同一个原则而构建", sub: "六大支柱，一个平台。从旅行梦想萌生的那一刻，到归来的那一刻，为您提供所需的一切。" },
      pillarNav: "跳至章节",
      pillars: [
        { category: "规划", tagline: "以您的方式规划旅行", description: "NativeWay 的规划套件远不止一个基础行程表。从零创建旅行，或让 AI 根据您的日期、预算、旅行风格和真实本地景点生成完整的逐日计划。", items: [{ title: "创建行程", description: "在同一视图中构建包含日期、目的地和已保存地点的多日旅行计划。" }, { title: "AI 行程规划", description: "用日常语言描述您的旅行，获取基于经过验证的本地推荐的完整行程。" }, { title: "路线规划", description: "自动优化停靠点顺序，让您不再原路折返。" }] },
        { category: "发现", tagline: "找到旅行指南所遗漏的", description: "NativeWay 的发现功能由人驱动，而非算法。数据库中的每一个地点都由真正住在那里的人添加。浏览精选目的地指南，按街区或氛围筛选。", items: [{ title: "本地地点", description: "地图上的每个标注都来自经过验证的居民——餐厅、公园、观景台、商店等。" }, { title: "隐藏宝藏", description: "当地人钟爱、游客几乎从未发现的精选地点。设计上防止病毒式传播。" }, { title: "目的地指南", description: "由每座城市居民撰写和维护的街区级完整指南。" }] },
        { category: "协作", tagline: "共同规划，畅游其中", description: "组团旅行出了名地难以组织。NativeWay 的协作工具让每个人真正站到同一起跑线上。共享行程板，民主投票，到达后启动派对模式。", items: [{ title: "派对模式", description: "到达时激活。实时查看每个人的位置，共享现场推荐，协调行动。" }, { title: "投票", description: "将候选地点添加到共享板并让大家投票。告别漫无止境的讨论串。" }, { title: "团队规划", description: "共享的行程板，每位成员在出发前后都可以编辑、评论和添加内容。" }] },
        { category: "管理", tagline: "所有旅行事务一站管理", description: "NativeWay 处理旅行的实务部分，让您专注于体验本身。安全存储护照信息，追踪签证要求，整理所有文件。", items: [{ title: "护照", description: "安全存储护照信息，并在到期前收到提醒。" }, { title: "签证", description: "获取目的地专属的签证要求、处理时间和官方申请门户链接。" }, { title: "旅行收藏", description: "将地点、文章和贴士保存到命名收藏夹，随时查阅、分享或转化为旅行计划。" }] },
        { category: "连接", tagline: "故事、对话、社群", description: "旅行在分享中变得更有意义。NativeWay 的社群层让旅行者和当地人交流故事、提问解答，建立超越单次旅行的连接。", items: [{ title: "博客", description: "撰写旅行报告和本地特辑。最佳故事将被收录进目的地指南。" }, { title: "消息", description: "与当地人和同行旅行者直接私信——寻求建议、表达感谢或保持联系。" }, { title: "社区", description: "按城市组织的论坛和话题。出发前提问，在途中分享，归来后回味。" }] },
        { category: "高级版", tagline: "解锁完整的 NativeWay 体验", description: "NativeWay 核心功能免费。高级版解锁更智能的 AI 规划、完整离线城市，以及刻意保留在免费版之外的专属本地发现。", items: [{ title: "AI 增强", description: "更智能的行程生成、个性化每日重新规划和 AI 驱动的「问问当地人」摘要。" }, { title: "离线访问", description: "下载任意城市——地图、评价、指南和路线——无需移动数据即可使用所有内容。" }, { title: "专属发现", description: "仅限高级版的隐藏宝藏，从公共地图上隐去，保护敏感地点免受过度旅游侵害。" }] },
      ],
      comingSoon: { badge: "即将推出", heading: "路线图上的功能", items: [{ title: "本地提醒", description: "获取目的地临时关闭、新开业及限时本地贴士的通知。" }, { title: "诈骗预警", description: "居民实时标记旅游诈骗和高价区域。" }, { title: "文化注意事项", description: "由见过游客犯错的居民撰写的礼仪贴士和本地习俗。" }, { title: "行程导出", description: "将已保存的地点和路线导出为可打印的 PDF 或直接与旅行伙伴分享。" }] },
      cta: { heading: "想第一个使用这些功能？", sub: "早期访问成员第一年免费获得所有内容。", button: "加入候补名单" },
    },
    howItWorksPage: {
      hero: { badge: "使用方式", heading: "从灵感到体验——每一步都有覆盖", sub: "NativeWay 支持完整的旅行旅程：出发前规划、到达后探索、与团队协作，以及归来后与社区连接。" },
      phases: ["规划", "发现", "协作", "导航", "分享"],
      steps: [
        { phase: "出发前", title: "规划您的旅行", description: "首先在 NativeWay 中创建旅行。设置目的地、日期和旅行风格。AI 行程生成器随后根据真实的本地推荐生成完整的逐日计划。", features: [{ label: "AI 行程", note: "日常语言输入 → 完整本地行程" }, { label: "路线规划", note: "自动排序，减少折返" }, { label: "护照与签证", note: "预订前查看要求" }], tip: "出发前下载目的地城市——一旦保存，所有功能均可离线使用。" },
        { phase: "出发前", title: "发现本地地点", description: "浏览本地地图，阅读居民撰写的目的地指南，将必去之处保存到行程板。使用隐藏宝藏功能发现永远不会出现在旅游杂志上的地方。", features: [{ label: "本地地点", note: "每个标注均由经过验证的居民放置" }, { label: "隐藏宝藏", note: "高级精选，不在公共地图上显示" }, { label: "目的地指南", note: "当地人撰写的街区级指南" }], tip: "将地点保存到命名收藏夹，让您的行程板井然有序。" },
        { phase: "与他人同行", title: "与团队协作", description: "与旅行伙伴共享行程板。每个人都可以添加建议，团队对最喜欢的选项投票。到达目的地后激活派对模式实时协调。", features: [{ label: "投票", note: "民主筛选——每个人都有发言权" }, { label: "派对模式", note: "全员到达后的实时协调" }, { label: "共享行程板", note: "每个人编辑同一旅行计划" }], tip: "设置投票截止时间，让规划不会无限拖延。" },
        { phase: "在途中", title: "导航与体验", description: "带着已下载的离线地图、本地路线和当地贴士出发。逐步跟随日间路线，或以本地地图为向导自由探索。", features: [{ label: "离线地图", note: "无需移动数据的完整导航" }, { label: "本地路线", note: "跟随当地人打造的了解每条捷径的路线" }, { label: "问问当地人", note: "经过验证的居民的实时回答" }], tip: "随走随标记已访问的地点——它会建立您的个人旅行历史。" },
        { phase: "旅行结束后", title: "分享与连接", description: "撰写旅行博客，对访问过的地点留下真实评价，并向帮助过您的当地人发送消息。您的旅行者视角为本地声音增添了宝贵的一层。", features: [{ label: "博客", note: "帮助未来旅行者的旅行报告" }, { label: "评价", note: "您的真实看法，叠加在本地评价之上" }, { label: "旅行收藏", note: "保存并整理一切，为下次旅行做准备" }], tip: "最有用的评价会提到其他评价中没有提到的一件具体事情。" },
      ],
      locals: { heading: "对当地人而言", steps: [{ number: "01", title: "验证您的居住地", description: "快速且隐私——无需存储敏感文件即可确认您住在该城市。水电账单或本地身份证即可。" }, { number: "02", title: "标注您喜爱的地方", description: "添加您真正热爱的地方——您的街区咖啡馆、视野最佳的公园、祖父母那一代就在那里的市场摊位。" }, { number: "03", title: "写下真实评价", description: "如实说：最佳菜品、最差访问时间、游客照片中看不到的东西。当地人是 NativeWay 上的真相讲述者。" }, { number: "04", title: "创建本地路线", description: "将您最爱的地点串联成一日行程。添加背景、历史和各站之间的旅途。打造一份您愿意送给朋友的指南。" }], note: "当地人获得声誉、认可，以及（即将推出的）来自感激旅行者的打赏。" },
      cta: { heading: "准备好亲自体验了吗？", sub: "注册早期访问，成为最先探索的人之一。", button: "提前获取" },
    },
    valuesPage: {
      hero: { badge: "我们的价值观", heading: "我们真正坚守的立场", sub: "价值观不是营销页面——它们是我们在付出代价时所做的决定。以下是我们的承诺，以及背后的原因。" },
      values: [
        { title: "真实性优先", summary: "每条推荐都来自真实的当地居民，而非网红。", description: "我们基于一个简单信念构建了 NativeWay：最有价值的旅行信息来自真正住在某地的人。不是算法、不是网红、不是两年前写就的旅行指南。", principles: ["当地人贡献内容前必须验证居住地", "无付费推广或赞助推荐", "内容需经多位当地人审核后才会展示", "每条条目均有透明标签"], quote: "\"如果我妈不会在那里吃饭，它就不会上地图。\" — Rania，社区负责人" },
        { title: "社区驱动", summary: "整个生态系统建立在当地人与旅行者的相互信任之上。", description: "NativeWay 是一个因当地人诚实贡献、旅行者真诚回应而不断进步的活系统。双方都有义务，双方都受益。", principles: ["当地人赚取声誉，不只是感谢", "旅行者需要留下诚实、具体的反馈", "社区管理员举报不良行为者", "平台变更决策参考社区意见"], quote: "\"诚实优先于客气。我们尽可能两者兼顾，但诚实优先。\" — Mateo，CEO" },
        { title: "支持本地", summary: "我们有意将旅游业引向独立商家和本地文化。", description: "大众旅游掏空了无数城市中心。NativeWay 将目光和金钱主动引向那些让目的地值得一访的地方。", principles: ["发现功能中独立商家始终优先", "连锁店不会出现在本地推荐中", "文化和遗产场所获得专属推广", "NativeWay 将2%的收入捐赠给本地保护基金"], quote: "\"您能带回家的最好纪念品，是知道您把钱花在了真正需要它的地方。\" — Aiko，CTO" },
        { title: "隐私设计", summary: "您的数据属于您。句号。", description: "旅游行业建立在数据提取之上。NativeWay 基于完全相反的模式构建。我们在您从应用中发现价值时获利。", principles: ["位置数据永远不会出售给第三方", "不进行广告行为追踪", "最小化数据收集：只获取产品所需的内容", "随时可导出完整数据和删除账户"], quote: "\"我们本可以通过出售您的数据赚更多钱。我们选择不这样做。\" — Diego，设计负责人" },
        { title: "可持续旅行", summary: "我们关注目的地的长期健康，而非仅仅是访客数量。", description: "过度旅游摧毁了使目的地具有吸引力的特质。NativeWay 内置了有意识管理访客流量的功能。", principles: ["隐藏宝藏的可见度受限，防止病毒式过度拥挤", "每个目的地页面均有文化礼仪指南", "通过季节性本地内容推广淡季旅行", "与本地环保组织合作"], quote: "\"我们希望我们热爱的地方，在20年后依然值得热爱。\" — Rania，社区负责人" },
        { title: "彻底透明", summary: "我们告诉您背后的运作方式——因为您值得知道。", description: "NativeWay 公开其内容审核准则、本地验证流程和商业模式。如果做出重大改变，我们会首先告知社区。", principles: ["公开内容审核政策", "平台更新的公开更新日志", "清晰说明商业模式：订阅制，无广告", "发布社区反馈（包括批评性反馈）"], quote: "\"信任通过展示您的工作来建立。每一次都是。\" — Mateo，CEO" },
      ],
      commitment: { heading: "这些不是愿望——而是约束", p1: "我们将价值观转化为硬性产品规则。即使我们想要，也无法插入赞助推荐——系统不允许。", p2: "这就是价值声明与价值观之间的区别。我们将约束内建其中。" },
      cta: { heading: "认同我们的价值观？来加入我们吧。", sub: "早期访问已开放——第一年免费。", button: "提前获取" },
    },
  },

  tr: {
    aboutPage: {
      hero: { badge: "Hikayemiz", heading: "Seyahatin insani hissettirmesi gerektiğine inanıyoruz", sub: "NativeWay basit bir hayal kırıklığından doğdu — her şehirdeki en iyi deneyimler, onlara en çok ihtiyaç duyan kişilerden gizli. Bunu değiştiriyoruz." },
      mission: [
        { title: "Misyonumuz", text: "Turistler ve yerliler arasındaki uçurumu kapatmak — her gezginin ait hissetmesini, her yerlinin duyulduğunu hissetmesini sağlamak." },
        { title: "Vizyonumuz", text: "Seyahatin gerçek kültürel alışverişe yol açtığı, yerel ekonomileri desteklediği ve destinasyonları daha iyi bıraktığı bir dünya." },
        { title: "Yaklaşımımız", text: "İnsan bağlantısının hizmetinde teknoloji. Kenara çekilip gerçek deneyimin parlamasına izin veren araçlar inşa ediyoruz." },
      ],
      origin: {
        badge: "Başlangıç Noktası", heading: "Barselona'daki kötü bir yemekten doğdu",
        p1: "2022 yılıydı. Mateo, La Rambla'dan üç blok uzakta mikrodalga fırından çıkmış bir paella için 28 Euro ödemişti. Metroda bir yerli ise ona Gràcia'daki aile restoranından bahsetti — 40 yıldır açık, hayatının en iyi pilavı için 12 Euro.",
        p2: "\"Bu bilgi neden bulunamıyor?\" diye sordu. Yanıt rahatsız ediciydi: çünkü seyahat keşfine hâkim platformlar özgünlük değil reklam için optimize edilmiş.",
        p3: "O gece Aiko'yu aradı. Altı ay sonra prototipleri vardı. İki yıl sonra 1.200 kişi bekleme listesinde. Gràcia'daki restoran? Hâlâ faaliyette.",
      },
      timeline: {
        badge: "Yolculuk", heading: "Buraya nasıl geldik",
        milestones: [
          { year: "2022", title: "Fikir kıvılcımı", description: "Mateo ve Aiko Lizbon'da bir hostelde tanışıyor ve aynı hayal kırıklığı etrafında bağ kuruyor: en iyi yerel mekânlar turistler için görünmez." },
          { year: "2023", title: "Temeller atılıyor", description: "5 şehirde 200 yerel ile ilk prototip test edildi. Geri bildirim çığır açıcıydı — yerliler şehirlerini paylaşmak için bir platform istiyordu." },
          { year: "2024", title: "Ekip büyüyor", description: "Rania ve Diego katılıyor. NativeWay yerel ağını 20 şehre genişletiyor ve kapalı beta testine başlıyor." },
          { year: "2025", title: "Bekleme listesi açılıyor", description: "İlk ayda 1.200'den fazla gezgin kaydoluyor. 50'den fazla şehirdeki ortak yerliler ilk koleksiyonlarını oluşturuyor." },
          { year: "2026", title: "Lansman yılı", description: "NativeWay halka açık lansmanına hazırlanıyor. Misyon basit: her gezginin kendini yerel gibi hissettirmek." },
        ],
      },
      team: { badge: "Ekip", heading: "Gezginler tarafından, gezginler için kuruldu" },
      cta: { heading: "Yerli gibi seyahat etmeye hazır mısınız?", sub: "Bekleme listesine katılın ve ilk deneyimleyenlerden olun.", button: "Erken Erişim Alın" },
    },
    featuresPage: {
      hero: { badge: "Özellikler", heading: "Her şey tek bir ilkeyle inşa edildi", sub: "Altı sütun. Bir platform. Seyahat hayalinden eve dönüşe kadar ihtiyacınız olan her şey." },
      pillarNav: "Bölüme atla",
      pillars: [
        { category: "Planla", tagline: "Gezini kendi tarzında planla", description: "NativeWay'in planlama paketi basit bir rota listesinin çok ötesinde. Sıfırdan seyahat oluşturun ya da AI'nın tarihlerinize, bütçenize ve seyahat tarzınıza göre tam bir günlük plan oluşturmasına izin verin.", items: [{ title: "Gezi Oluştur", description: "Tarihleri, destinasyonları ve kayıtlı yerleri tek görünümde içeren çok günlü seyahat panoları oluşturun." }, { title: "AI Rotaları", description: "Gezinizi günlük dille tanımlayın, doğrulanmış yerel önerilerden eksiksiz bir rota alın." }, { title: "Güzergah Planlaması", description: "Durakların sırasını otomatik optimize ederek geri dönme sorununun önüne geçin." }] },
        { category: "Keşfet", tagline: "Rehberlerin atladığını bul", description: "NativeWay'de keşif algoritmalar değil insanlar tarafından yönlendirilir. Veri tabanımızdaki her yer gerçekten orada yaşayan biri tarafından eklendi. Mahalleye veya ambiyansa göre filtreleyin.", items: [{ title: "Yerel Mekânlar", description: "Haritadaki her toplu iğne doğrulanmış bir sakindan geliyor — restoranlar, parklar, manzara noktaları ve daha fazlası." }, { title: "Gizli Hazineler", description: "Yerlilerin sevdiği ama turistlerin neredeyse hiç bulamadığı özenle seçilmiş mekânlar." }, { title: "Destinasyon Rehberleri", description: "Her şehirde yaşayan kişiler tarafından yazılan ve güncellenen mahalle mahalle tam rehberler." }] },
        { category: "İşbirliği Yap", tagline: "Birlikte planla, daha iyi seyahat et", description: "Grup seyahati organize etmesi güçtür. NativeWay'in araçları herkesi aynı sayfaya getirir. Seyahat panolarını paylaşın, demokratik oy kullanın ve Parti Modunu etkinleştirin.", items: [{ title: "Parti Modu", description: "Grubunuz geldiğinde etkinleştirin. Herkesin konumunu görün, öneriler paylaşın, gerçek zamanlı koordinasyon sağlayın." }, { title: "Oylama", description: "Aday yerleri paylaşılan panoya ekleyin ve grubun oy kullanmasına izin verin." }, { title: "Grup Planlaması", description: "Her üyenin seyahat öncesinde ve sırasında düzenleyebileceği paylaşılan seyahat panoları." }] },
        { category: "Yönet", tagline: "Tüm seyahat işlerini tek yerden", description: "NativeWay seyahatin pratik tarafını halleder, siz deneyime odaklanırsınız. Pasaport bilgilerini saklayın, vize gereksinimlerini takip edin, tüm belgelerinizi düzenleyin.", items: [{ title: "Pasaport", description: "Pasaport bilgilerinizi güvenle saklayın ve son kullanma tarihinden önce hatırlatıcı alın." }, { title: "Vize", description: "Destinasyona özel vize gereksinimleri, işlem süreleri ve resmi başvuru portalı bağlantıları alın." }, { title: "Seyahat Koleksiyonları", description: "Yerleri, makaleleri ve ipuçlarını adlandırılmış koleksiyonlara kaydedin, tekrar ziyaret edin veya seyahate dönüştürün." }] },
        { category: "Bağlan", tagline: "Hikayeler, sohbetler, topluluk", description: "Seyahat paylaştığınızda daha anlamlı hale gelir. NativeWay'in topluluk katmanı gezginlerin ve yerlilerin hikaye alışverişi yapmasını ve bağlar kurmasını sağlar.", items: [{ title: "Bloglar", description: "Gezi raporları ve yerel öne çıkarma yazıları yazın. En iyi hikayeler destinasyon rehberlerinde öne çıkar." }, { title: "Mesajlaşma", description: "Yerlilerle ve diğer gezginlerle doğrudan mesajlaşın." }, { title: "Topluluk", description: "Şehre göre düzenlenmiş forum ve konular. Gitmeden sorun, oradayken paylaşın, döndükten sonra değerlendirin." }] },
        { category: "Premium", tagline: "Tam NativeWay deneyiminin kilidini açın", description: "NativeWay'in özü ücretsiz. Premium, daha akıllı AI planlaması, tam çevrimdışı şehirler ve özel yerel keşifler sunar.", items: [{ title: "AI Geliştirmeleri", description: "Daha akıllı rota oluşturma, kişiselleştirilmiş günlük yeniden planlama ve AI destekli Yerli'ye Sor özetleri." }, { title: "Çevrimdışı Erişim", description: "Herhangi bir şehri indirin — haritalar, yorumlar, rehberler ve rotalar — mobil veri olmadan kullanın." }, { title: "Özel Keşifler", description: "Aşırı turizmin yıkımından korumak amacıyla genel haritadan gizlenen yalnızca premium üyelere özel gizli hazineler." }] },
      ],
      comingSoon: { badge: "Yakında", heading: "Yol haritasında", items: [{ title: "Yerel Uyarılar", description: "Destinasyonunuzdaki geçici kapanışlar ve yeni açılışlar hakkında bildirim alın." }, { title: "Dolandırıcılık Uyarıları", description: "Sakinler turist tuzaklarını ve aşırı fiyatlı alanları gerçek zamanlı işaretler." }, { title: "Kültürel Notlar", description: "Turistlerin hata yaptığını gören sakinlerin yazdığı görgü kuralları ve yerel gelenekler." }, { title: "Gezi Dışa Aktarma", description: "Kayıtlı yerlerinizi yazdırılabilir PDF olarak dışa aktarın veya seyahat arkadaşlarınızla paylaşın." }] },
      cta: { heading: "Bu özellikleri ilk kullananlardan olmak ister misiniz?", sub: "Erken erişim üyeleri bir yıl boyunca her şeyi ücretsiz alır.", button: "Bekleme Listesine Katıl" },
    },
    howItWorksPage: {
      hero: { badge: "Nasıl Çalışır", heading: "Fikirden deneyime — her adım kapsanıyor", sub: "NativeWay tam seyahat yolculuğunu destekler: gitmeden önce planlama, oradayken keşfetme, grubunuzla işbirliği ve sonrasında toplulukla bağlantı." },
      phases: ["Planla", "Keşfet", "İşbirliği Yap", "Gezin", "Paylaş"],
      steps: [
        { phase: "Gitmeden Önce", title: "Gezini planla", description: "NativeWay'de bir gezi oluşturarak başlayın. Destinasyonunuzu, tarihlerinizi ve seyahat tarzınızı belirleyin. AI rota oluşturucumuz gerçek yerel önerileri kullanarak tam günlük plan oluşturur.", features: [{ label: "AI Rotaları", note: "Günlük dil → tam yerel rota" }, { label: "Güzergah Planlaması", note: "Geri dönüşü azaltmak için sıralama" }, { label: "Pasaport & Vize", note: "Rezervasyondan önce kontrol et" }], tip: "Gitmeden önce destinasyon şehrinizi indirin — bir kez kaydedildiğinde her şey çevrimdışı çalışır." },
        { phase: "Gitmeden Önce", title: "Yerel mekânları keşfet", description: "Yerel haritayı gezin, sakinlerin yazdığı destinasyon rehberlerini okuyun ve mutlaka gidilecek yerleri seyahat panosuna kaydedin. Gizli Hazineler'i kullanarak hiçbir seyahat dergisinde görünmeyecek yerleri bulun.", features: [{ label: "Yerel Mekânlar", note: "Her toplu iğne doğrulanmış bir sakin tarafından" }, { label: "Gizli Hazineler", note: "Premium seçkisi, genel haritadan gizli" }, { label: "Destinasyon Rehberleri", note: "Yerlilerin mahalle rehberleri" }], tip: "Panoyu düzenli tutmak için yerleri adlandırılmış koleksiyonlara kaydedin." },
        { phase: "Başkalarıyla Seyahat Ederken", title: "Grubunuzla işbirliği yap", description: "Seyahat panonuzu seyahat arkadaşlarınızla paylaşın. Her kişi öneri ekleyebilir ve grup en beğendikleri seçeneklere oy kullanır. Yere ayak bastığınızda Parti Modunu etkinleştirin.", features: [{ label: "Oylama", note: "Demokratik eleme — herkesin söz hakkı var" }, { label: "Parti Modu", note: "Hepiniz oradayken canlı koordinasyon" }, { label: "Paylaşılan Panolar", note: "Herkes aynı seyahat planını düzenler" }], tip: "Planlamanın sonsuzlaşmaması için oylama son tarihi belirleyin." },
        { phase: "Yolda", title: "Gezin ve deneyimle", description: "Çevrimdışı haritanız, yerel rotalarınız ve yerel ipuçlarınız indirilmiş halde çıkın. Adım adım bir günlük rotayı takip edin ya da yerel haritayı rehber olarak serbest keşfe çıkın.", features: [{ label: "Çevrimdışı Haritalar", note: "Mobil veri olmadan tam navigasyon" }, { label: "Yerel Rotalar", note: "Her kestirmeyi bilen yerlilerin rotaları" }, { label: "Yerliye Sor", note: "Doğrulanmış sakinlerden gerçek zamanlı yanıtlar" }], tip: "Giderken ziyaret ettiğiniz yerleri işaretleyin — kişisel seyahat geçmişinizi oluşturur." },
        { phase: "Seyahatten Sonra", title: "Paylaş ve bağlan", description: "Bir gezi blogu yazın, ziyaret ettiğiniz yerlere dürüst yorumlar bırakın ve yardımcı olan yerlilere mesaj gönderin. Gezgin bakış açınız yerel sese değerli bir katman ekler.", features: [{ label: "Bloglar", note: "Gelecekteki gezginlere yardımcı olan gezi raporları" }, { label: "Yorumlar", note: "Yerel yorumların üzerine eklenen dürüst görüşünüz" }, { label: "Seyahat Koleksiyonları", note: "Her şeyi bir sonraki seyahat için kaydedin" }], tip: "En kullanışlı yorumlar başka hiçbir yorumun belirtmediği belirli bir şeyden bahseder." },
      ],
      locals: { heading: "Yerliler İçin", steps: [{ number: "01", title: "İkametinizi doğrulayın", description: "Hızlı ve gizli — hassas belgeleri saklamadan şehirde yaşadığınızı doğruluyoruz." }, { number: "02", title: "Sevdiğiniz yerleri işaretleyin", description: "Gerçekten sevdiğiniz yerleri ekleyin — mahalledeki kafen, en iyi manzaralı park, büyükbaba zamanından beri orada olan pazar tezgahı." }, { number: "03", title: "Dürüst yorumlar yazın", description: "Olduğu gibi söyleyin: en iyi yemek, en kötü ziyaret saati, turist fotoğraflarının göstermediği şeyler." }, { number: "04", title: "Yerel Rota oluşturun", description: "Favori yerlerinizi bir günlük programa dönüştürün. Bağlam, tarih ve duraklar arasındaki yolculuğu ekleyin." }], note: "Yerliler itibar, tanınma ve (yakında) minnettar gezginlerden bahşiş kazanır." },
      cta: { heading: "Kendiniz denemek ister misiniz?", sub: "Erken erişime kaydolun ve ilk keşfedenlerden biri olun.", button: "Erken Erişim Alın" },
    },
    valuesPage: {
      hero: { badge: "Değerlerimiz", heading: "Gerçekten neyin yanında durduğumuz", sub: "Değerler bir pazarlama sayfası değil — bir maliyeti olduğunda verdiğimiz kararlardır. İşte taahhüt ettiğimiz şeyler ve nedenleri." },
      values: [
        { title: "Önce Özgünlük", summary: "Her öneri gerçek yerel sakinlerden gelir, fenomenlerden değil.", description: "NativeWay'i basit bir inançla inşa ettik: en değerli seyahat bilgisi gerçekten bir yerde yaşayan insanlardan gelir. Algoritmalardan değil, iki gece konaklayan fenomenlerden değil, eski rehberlerden değil.", principles: ["Yerliler katkıda bulunmadan önce ikametlerini doğrulamalıdır", "Ücretli yerleştirme veya sponsorlu tavsiyeler yoktur", "İçerik gösterilmeden önce birden fazla yerel tarafından incelenir", "Her girişte şeffaflık etiketleri"], quote: "\"Annem orada yemek yemez ise, haritaya girmez.\" — Rania, Topluluk Başkanı" },
        { title: "Topluluk Odaklı", summary: "Tüm ekosistem yerliler ve gezginler arasındaki karşılıklı güvene dayanır.", description: "NativeWay, yerlilerin dürüstçe katkıda bulunması ve gezginlerin gerçek takdirle karşılık vermesiyle gelişen canlı bir sistemdir. Her iki tarafın yükümlülükleri ve faydaları vardır.", principles: ["Yerliler yalnızca teşekkür değil itibar kazanır", "Gezginlerin dürüst spesifik geri bildirim bırakması beklenir", "Topluluk moderatörleri kötü aktörleri işaretler", "Platform değişikliklerine ilişkin kararlar topluluk girdisiyle bilgilendirilir"], quote: "\"Dürüstlük kibarlığa tercih edilmeli. İkisini de isteriz ama dürüstlük önce gelir.\" — Mateo, CEO" },
        { title: "Yereli Destekle", summary: "Turizmi kasıtlı olarak bağımsız işletmelere ve yerel kültüre yönlendiriyoruz.", description: "Kitlesel turizm pek çok şehir merkezini boşalttı. NativeWay bir destinasyonu ziyaret etmeye değer kılan yerlere dikkati ve parayı aktif olarak yönlendirmek için var.", principles: ["Bağımsız işletmeler keşifte her zaman öncelikli", "Zincir işletmeler yerel önerilerde görünmez", "Kültürel ve miras alanları özel tanıtım alır", "NativeWay gelirinin %2'sini yerel koruma fonlarına bağışlar"], quote: "\"Eve götürebileceğiniz en iyi hatıra paranızı gerçekten ihtiyaç duyan bir yere harcadığınızı bilmektir.\" — Aiko, CTO" },
        { title: "Tasarımda Gizlilik", summary: "Verileriniz sizindir. Nokta.", description: "Seyahat endüstrisi veri çıkarmaya dayanır. NativeWay tam tersi modele göre inşa edilmiştir. Uygulamada değer bulduğunuzda para kazanırız.", principles: ["Konum verileri hiçbir zaman üçüncü taraflara satılmaz", "Reklam amaçlı davranışsal izleme yoktur", "Minimum veri toplama: yalnızca ürünün ihtiyaç duyduğu şey", "Tam veri dışa aktarma ve hesap silme her zaman mevcut"], quote: "\"Verilerinizi satarak daha fazla para kazanabilirdik. Seçmedik.\" — Diego, Tasarım" },
        { title: "Sürdürülebilir Seyahat", summary: "Ziyaretçi sayısından ziyade destinasyonların uzun vadeli sağlığını düşünüyoruz.", description: "Aşırı turizm bir destinasyonu çekici kılan özellikleri yok eder. NativeWay ziyaretçi akışını bilinçli olarak yöneten özelliklerle inşa edilmiştir.", principles: ["Gizli Hazineler görünürlüğü viral kalabalığı önlemek için sınırlıdır", "Her destinasyon sayfasında kültürel görgü rehberleri", "Mevsimsel yerel içerikle sezon dışı seyahat teşvik edilir", "Yerel çevre gruplarıyla ortaklıklar"], quote: "\"Sevdiğimiz yerlerin 20 yıl sonra da sevilmeye değer olmasını istiyoruz.\" — Rania, Topluluk Başkanı" },
        { title: "Radikal Şeffaflık", summary: "Size işin iç yüzünü anlatıyoruz — çünkü bunu bilmeyi hak ediyorsunuz.", description: "NativeWay içerik moderasyon yönergelerini, yerel doğrulama sürecini ve iş modelini açıkça yayımlar. Önemli değişikliklerde önce topluluğa söyleriz.", principles: ["Kamuya açık içerik moderasyon politikası", "Platform güncellemelerinin açık değişiklik günlüğü", "İş modeli açıkça açıklandı: abonelik, reklam yok", "Eleştirel olanlar dahil topluluk geri bildirimi yayımlandı"], quote: "\"Güven çalışmanızı göstererek inşa edilir. Her seferinde.\" — Mateo, CEO" },
      ],
      commitment: { heading: "Bunlar birer özlem değil — kısıtlamalardır", p1: "Değerlerimizi katı ürün kurallarına dönüştürdük. İstsek de sponsorlu öneri ekleyemeyiz — sistem izin vermiyor. Konum verisi satamayız — satabileceğimiz formda toplamıyoruz.", p2: "Değer beyanı ile değer arasındaki fark budur. Kısıtlamaları içine inşa ediyoruz." },
      cta: { heading: "Değerlerimizi paylaşıyor musunuz? Gelin katılın.", sub: "Erken erişim açık — ve ilk yıl ücretsiz.", button: "Erken Erişim Alın" },
    },
  },

  no: {
    aboutPage: {
      hero: { badge: "Vår historie", heading: "Vi tror reisen bør føles menneskelig", sub: "NativeWay ble født av en enkel frustrasjon — de beste opplevelsene i enhver by er skjult for dem som trenger dem mest. Det endrer vi på." },
      mission: [
        { title: "Vårt oppdrag", text: "Å tette gapet mellom turister og lokalbefolkning — slik at enhver reisende føler tilhørighet, og enhver lokal føler seg hørt." },
        { title: "Vår visjon", text: "En verden der reise skaper ekte kulturutveksling, støtter lokale økonomier og etterlater destinasjoner bedre enn vi fant dem." },
        { title: "Vår tilnærming", text: "Teknologi i menneskelig tilkoblings tjeneste. Vi bygger verktøy som trekker seg tilbake og lar den ekte opplevelsen skinne gjennom." },
      ],
      origin: {
        badge: "Opprinnelsen", heading: "Født av et dårlig måltid i Barcelona",
        p1: "Det var 2022. Mateo hadde nettopp betalt 28 euro for en paella fra mikrobølgeovnen, tre kvartaler fra La Rambla. En lokal på T-banen fortalte ham om en familiedrevet restaurant i Gràcia — åpen i 40 år, full av faste gjester, 12 euro for den beste risen han noensinne hadde spist.",
        p2: "\"Hvorfor er ikke denne informasjonen søkbar?\" spurte han. Svaret var ubehagelig: fordi plattformene som dominerer reiseoppdagelse er optimalisert for annonsekroner, ikke autentisitet.",
        p3: "Han ringte Aiko den kvelden. Seks måneder senere hadde de en prototype. To år senere er 1 200 personer på ventelisten. Paella-restauranten i Gràcia er fortsatt i full drift.",
      },
      timeline: {
        badge: "Reisen", heading: "Slik kom vi hit",
        milestones: [
          { year: "2022", title: "Idéen oppstår", description: "Mateo og Aiko møtes på et hostel i Lisboa og finner hverandre i den samme frustrasjonen: de beste lokale stedene er usynlige for turister." },
          { year: "2023", title: "Grunnlaget bygges", description: "Første prototype testet med 200 lokale på tvers av 5 byer. Tilbakemeldingene var overveldende — lokale ville ha en plattform for å dele sin by." },
          { year: "2024", title: "Teamet vokser", description: "Rania og Diego kommer om bord. NativeWay utvider sitt lokale nettverk til 20 byer og begynner lukket betatesting." },
          { year: "2025", title: "Ventelisten åpner", description: "Over 1 200 reisende registrerer seg i løpet av den første måneden. Partnerlokale i 50+ byer kuraterer sine første samlinger." },
          { year: "2026", title: "Lanseringsår", description: "NativeWay forbereder offentlig lansering. Oppdraget er enkelt: få enhver reisende til å føle seg som en lokal." },
        ],
      },
      team: { badge: "Teamet", heading: "Bygget av reisende, for reisende" },
      cta: { heading: "Klar til å reise på den lokale måten?", sub: "Bli med på ventelisten og vær den første til å oppleve det.", button: "Få tidlig tilgang" },
    },
    featuresPage: {
      hero: { badge: "Funksjoner", heading: "Alt bygget etter ett prinsipp", sub: "Seks pilarer. Én plattform. Alt du trenger fra det øyeblikket du begynner å drømme om en tur til du er hjemme igjen." },
      pillarNav: "Gå til seksjon",
      pillars: [
        { category: "Planlegg", tagline: "Bygg turen din, på din måte", description: "NativeWays planleggingssuite går langt utover en enkel reiseplan. Lag turer fra bunnen av eller la vår AI generere en fullstendig daglig plan basert på dine datoer, budsjett og reisestil.", items: [{ title: "Opprett turer", description: "Bygg flerdagers turpaneler med datoer, destinasjoner og lagrede steder i én visning." }, { title: "AI-reiseplaner", description: "Beskriv turen din i hverdagsspråk og få en fullstendig reiseplan fra verifiserte lokale anbefalinger." }, { title: "Ruteplanlegging", description: "Optimaliser rekkefølgen på stoppene automatisk slik at du ikke dobler tilbake gjennom byen." }] },
        { category: "Oppdag", tagline: "Finn det guidebøkene går glipp av", description: "Oppdagelse på NativeWay er drevet av mennesker, ikke algoritmer. Hvert sted i databasen ble lagt til av noen som faktisk bor der. Bla gjennom kuraterte destinasjonsguider, filtrer etter nabolag eller stemning.", items: [{ title: "Lokale steder", description: "Hver nål på kartet kommer fra en verifisert beboer — restauranter, parker, utsiktspunkter, butikker og mer." }, { title: "Skjulte perler", description: "Et kuratert lag med steder som lokale elsker, men turister nesten aldri finner." }, { title: "Destinasjonsguider", description: "Fullstendige nabolag-for-nabolag-guider skrevet av folk som bor i hver by." }] },
        { category: "Samarbeid", tagline: "Planlegg sammen, reis bedre", description: "Gruppereis er vanskelig å organisere. NativeWays samarbeidsverktøy bringer alle på samme side. Del turpaneler, stem demokratisk og bruk Festmodus når dere alle er på bakken.", items: [{ title: "Festmodus", description: "Aktiver når gruppen ankommer. Se hvor alle er, del live-anbefalinger og koordiner i sanntid." }, { title: "Stemming", description: "Legg til kandidatsteder i et delt panel og la gruppen stemme. Ikke mer endeløse meldingstråder." }, { title: "Gruppeplanlegging", description: "Delte turpaneler som hvert medlem kan redigere, kommentere og legge til før og under turen." }] },
        { category: "Administrer", tagline: "All reiseadministrasjon på ett sted", description: "NativeWay håndterer den praktiske siden av reisen slik at du kan fokusere på opplevelsen. Lagre passinformasjon, spor visumkrav og hold alle dokumenter organisert.", items: [{ title: "Pass", description: "Lagre passinformasjonen din sikkert og få påminnelser før den utløper." }, { title: "Visa", description: "Få destinasjonsspesifikke visumkrav, behandlingstider og lenker til offisielle søkerportaler." }, { title: "Reisesamlinger", description: "Lagre steder, artikler og tips i navngitte samlinger du kan gjenbesøke, dele eller gjøre om til en tur." }] },
        { category: "Koble til", tagline: "Historier, samtaler, fellesskap", description: "Reise er mer meningsfull når du deler den. NativeWays fellesskapslag lar reisende og lokale utveksle historier og bygge forbindelser utover en enkelt tur.", items: [{ title: "Blogger", description: "Skriv turrapporter og lokale høydepunkter. De beste historiene blir fremhevet i destinasjonsguider." }, { title: "Meldinger", description: "Direkte meldinger med lokale og medreisende — be om råd, si takk eller hold kontakten." }, { title: "Fellesskap", description: "Fora og tråder organisert etter by. Spør før du reiser, del mens du er der, reflekter når du er tilbake." }] },
        { category: "Premium", tagline: "Lås opp hele NativeWay-opplevelsen", description: "NativeWays kjerne er gratis. Premium låser opp rikere AI-planlegging, fullstendige frakoblede byer og tilgang til våre mest eksklusive lokale oppdagelser.", items: [{ title: "AI-forbedringer", description: "Smartere reiseplansgenerering, personlig daglig omplanlegging og AI-drevne sammendrag." }, { title: "Frakoblet tilgang", description: "Last ned hvilken som helst by — kart, anmeldelser, guider og ruter — bruk alt uten mobildata." }, { title: "Eksklusive oppdagelser", description: "Premium-only skjulte perler holdt av det offentlige kartet for å beskytte sårbare steder." }] },
      ],
      comingSoon: { badge: "Kommer snart", heading: "På veikartet", items: [{ title: "Lokale varsler", description: "Få varsler om midlertidige stenginger, nyåpninger og tidssensitive lokale tips." }, { title: "Svindeladvarsler", description: "Beboere merker turistsvindel og overprisede områder i sanntid." }, { title: "Kulturelle notater", description: "Etikette-tips og lokale skikker skrevet av beboere som har sett turister gjøre feil." }, { title: "Tureksport", description: "Eksporter lagrede steder og ruter som en utskrivbar PDF eller del med reisefølget ditt." }] },
      cta: { heading: "Vil du være blant de første til å bruke disse funksjonene?", sub: "Tidlig tilgang-medlemmer får alt gratis i et helt år.", button: "Bli med på ventelisten" },
    },
    howItWorksPage: {
      hero: { badge: "Slik fungerer det", heading: "Fra idé til opplevelse — hvert steg dekket", sub: "NativeWay støtter hele reisereisen: planlegging før du drar, oppdagelse mens du er der, samarbeid med gruppen, og kontakt med fellesskapet etterpå." },
      phases: ["Planlegg", "Oppdag", "Samarbeid", "Naviger", "Del"],
      steps: [
        { phase: "Før avreise", title: "Planlegg turen din", description: "Start med å opprette en tur i NativeWay. Sett destinasjon, datoer og reisestil. Vår AI genererer en fullstendig daglig plan ved hjelp av ekte lokale anbefalinger.", features: [{ label: "AI-reiseplaner", note: "Hverdagsspråk → fullstendig lokal plan" }, { label: "Ruteplanlegging", note: "Stopp sortert for å minimere tilbakekjøring" }, { label: "Pass og visa", note: "Sjekk krav før du bestiller" }], tip: "Last ned destinasjonsbyen din før du reiser — alt fungerer frakoblet når det er lagret." },
        { phase: "Før avreise", title: "Oppdag lokale steder", description: "Bla gjennom det lokale kartet, les destinasjonsguider skrevet av beboere, og lagre must-visits til et turpanel. Bruk Skjulte perler for å finne steder som aldri vil dukke opp i et reisemagasin.", features: [{ label: "Lokale steder", note: "Hver nål plassert av en verifisert beboer" }, { label: "Skjulte perler", note: "Premium-kuratert, holdt av offentlig kart" }, { label: "Destinasjonsguider", note: "Nabolagsnivå-guider av lokale" }], tip: "Lagre steder i navngitte samlinger for å holde panelet organisert." },
        { phase: "Reise med andre", title: "Samarbeid med gruppen din", description: "Del turpanelet ditt med reisefølget. Alle kan legge til forslag og gruppen stemmer på alternativene de liker mest. Aktiver Festmodus for sanntidskoordinering på stedet.", features: [{ label: "Stemming", note: "Demokratisk kortnedlisting — alle har en stemme" }, { label: "Festmodus", note: "Live-koordinering når dere alle er der" }, { label: "Delte paneler", note: "Alle redigerer samme turplan" }], tip: "Sett en stemningsfrist slik at planleggingen ikke drar ut i det uendelige." },
        { phase: "På stedet", title: "Naviger og opplev", description: "Dra ut med frakoblet kart, Native Routes og lokale tips allerede lastet ned. Følg en dagsrute steg for steg, eller utforsk fritt med det lokale kartet som guide.", features: [{ label: "Frakoblede kart", note: "Full navigering uten mobildata" }, { label: "Native Routes", note: "Følg ruter bygget av lokale som kjenner hver snarvei" }, { label: "Spør en lokal", note: "Sanntidssvar fra verifiserte beboere" }], tip: "Merk steder som besøkt underveis — det bygger din personlige reisehistorie." },
        { phase: "Etter turen", title: "Del og koble til", description: "Skriv en turlogg, legg igjen ærlige anmeldelser og send meldinger til lokale som hjalp deg. Ditt perspektiv legger til et verdifullt lag oppå den lokale stemmen.", features: [{ label: "Blogger", note: "Turrapporter som hjelper fremtidige reisende" }, { label: "Anmeldelser", note: "Din ærlige mening, lagdelt på lokale anmeldelser" }, { label: "Reisesamlinger", note: "Lagre og organiser alt til neste gang" }], tip: "De mest nyttige anmeldelsene nevner én spesifikk ting ingen annen anmeldelse nevner." },
      ],
      locals: { heading: "For lokale", steps: [{ number: "01", title: "Verifiser bostedet ditt", description: "Raskt og privat — vi bekrefter at du bor i byen uten å lagre sensitive dokumenter." }, { number: "02", title: "Fest favorittstedene dine", description: "Legg til steder du virkelig elsker — nabolagskafeen din, parken med best utsikt, markedsstanden som har vært der siden besteforeldres tid." }, { number: "03", title: "Skriv ærlige anmeldelser", description: "Si det som det er: beste rett, verste tidspunkt å besøke, hva turistbildene ikke viser." }, { number: "04", title: "Bygg en Native Route", description: "Koble favorittstedene dine til en dagstinerary. Legg til kontekst, historie og reisen mellom stopp." }], note: "Lokale tjener omdømme, anerkjennelse og (kommer snart) tips fra takknemlige reisende." },
      cta: { heading: "Klar til å prøve det selv?", sub: "Registrer deg for tidlig tilgang og vær blant de første til å utforske.", button: "Få tidlig tilgang" },
    },
    valuesPage: {
      hero: { badge: "Våre verdier", heading: "Hva vi faktisk står for", sub: "Verdier er ikke en markedsføringsside — de er beslutningene vi tar når det koster oss noe. Her er det vi har forpliktet oss til, og hvorfor." },
      values: [
        { title: "Autentisitet først", summary: "Alle anbefalinger kommer fra ekte lokale beboere — ikke influencere.", description: "Vi bygget NativeWay rundt en enkel tro: den mest verdifulle reiseinformasjonen kommer fra folk som faktisk bor et sted. Ikke algoritmer, ikke influencere, ikke utdaterte guidebøker.", principles: ["Lokale må verifisere bostedet sitt før de bidrar", "Ingen betalte plasseringer eller sponsede anbefalinger", "Innhold gjennomgås av flere lokale før det vises", "Åpenhetsetiketter på hvert oppslag"], quote: "\"Hvis mamma mi ikke ville spise der, kommer det ikke på kartet.\" — Rania, Fellesskapssjef" },
        { title: "Fellesskapsdrevet", summary: "Hele økosystemet drives av gjensidig tillit mellom lokale og reisende.", description: "NativeWay er et levende system som forbedres fordi lokale bidrar ærlig og reisende svarer med genuin takknemlighet. Begge sider har forpliktelser, begge sider tjener på det.", principles: ["Lokale tjener omdømme, ikke bare takk", "Reisende forventes å legge igjen ærlige, spesifikke tilbakemeldinger", "Fellesskapsmoderatorene flagger dårlige aktører", "Beslutninger om plattformendringer informeres av fellesskapsinput"], quote: "\"Ærlighet fremfor å være snill. Vi ber om begge deler der det er mulig, men ærlighet først.\" — Mateo, CEO" },
        { title: "Støtt lokalt", summary: "Vi styrer bevisst turisme mot uavhengige virksomheter og lokal kultur.", description: "Masseturisme har tømt utallige bysentre. NativeWay ruter aktivt oppmerksomhet og penger mot stedene som gjør en destinasjon verdt å besøke.", principles: ["Uavhengige virksomheter prioriteres alltid i oppdagelse", "Kjeder vises ikke i lokale anbefalinger", "Kulturelle og historiske steder får dedikert promotering", "NativeWay donerer 2% av inntektene til lokale bevvaringsfond"], quote: "\"Den beste suveniren du kan ta med hjem er å vite at du brukte penger et sted som trengte det.\" — Aiko, CTO" },
        { title: "Personvern by design", summary: "Dataene dine er dine. Punktum.", description: "Reisebransjen er bygget på datauttrekk. NativeWay er bygget på den motsatte modellen. Vi tjener penger når du finner verdi i appen.", principles: ["Ingen lokasjonsdata selges til tredjeparter — noensinne", "Ingen atferdssporing for reklame", "Minimal datainnsamling: bare det produktet trenger", "Full dataeksport og sletting av konto tilgjengelig når som helst"], quote: "\"Vi kunne tjent mer penger ved å selge dataene dine. Vi valgte ikke å gjøre det.\" — Diego, Design" },
        { title: "Bærekraftig reise", summary: "Vi tenker på den langsiktige helsen til destinasjoner, ikke bare besøkstall.", description: "Overturisme ødelegger de samme kvalitetene som gjorde en destinasjon attraktiv. NativeWay er bygget med funksjoner som bevisst styrer besøkendes strøm.", principles: ["Synlighet for skjulte perler er begrenset for å forhindre viral overbelastning", "Kulturelle etikette-guider på hver destinasjonsside", "Reise utenfor sesong fremmes med sesongbasert lokalt innhold", "Partnerskap med lokale miljøgrupper"], quote: "\"Vi vil at stedene vi elsker fortsatt skal være verdt å elske om 20 år.\" — Rania, Fellesskapssjef" },
        { title: "Radikal åpenhet", summary: "Vi forteller deg hvordan det henger sammen — fordi du fortjener å vite.", description: "NativeWay publiserer sine retningslinjer for innholdsmoderering, den lokale verifiseringsprosessen og forretningsmodellen åpent. Hvis vi endrer noe vesentlig, forteller vi fellesskapet først.", principles: ["Offentlig retningslinje for innholdsmoderering", "Åpen endringslogg for plattformoppdateringer", "Forretningsmodell tydelig forklart: abonnement, ingen annonser", "Fellesskapstilbakemeldinger publisert inkludert kritiske"], quote: "\"Tillit bygges ved å vise arbeidet ditt. Hver gang.\" — Mateo, CEO" },
      ],
      commitment: { heading: "Dette er ikke ambisjoner — det er begrensninger", p1: "Vi har gjort verdiene våre om til harde produktregler. Vi kan ikke sette inn en sponset anbefaling selv om vi ville — systemet tillater det ikke. Vi kan ikke selge lokasjonsdata — vi samler det ikke inn i en form som kan selges.", p2: "Det er forskjellen mellom en verdierklæring og en verdi. Vi bygger begrensningene inn." },
      cta: { heading: "Deler du våre verdier? Bli med oss.", sub: "Tidlig tilgang er åpen — og gratis det første året.", button: "Få tidlig tilgang" },
    },
  },
} as const;

export type PageTranslations = typeof pageTranslations.en;
